---
title: "Time Series descriptive statistics"
output: html_notebook
---

```{r}
library(forecast) # from the book Forecasting: Principles and Practice, OTexts, 2013
library(ggplot2)
```


Import Dataset, convert it to time series and plot it.

```{r}
data=read.csv(file="http://eric.univ-lyon2.fr/~jjacques/Download/DataSet/varicelle.csv")
varicelle<-ts(data$x,start=c(1931,1),end=c(1972,6),freq=12)
autoplot(varicelle) +
  ggtitle('Number of varicella per months')+
  xlab('year')+
  ylab('Number of varicella')
```

Seasonal plot

```{r}
ggseasonplot(varicelle,year.labels= TRUE,year.labels.left=TRUE)
```

Polar Seasonal plot

```{r}
ggseasonplot(varicelle,polar=TRUE)
```

descriptive stats for TS
empirical mean and variance

```{r}
mean(varicelle)
var(varicelle)
```

Empirical auto-covariance

```{r}
tmp=acf(varicelle,type="cov",plot = FALSE)
tmp$acf[1:3,1,1]
plot(tmp)
```

Empirical auto-correlation (between -1 and 1) 
plot called crelogram
between blue lines -> not significantly different from 0 (+-2/sqrt(n))

```{r}
tmp=acf(varicelle,type="cor",plot = FALSE)
tmp$acf[1:3,1,1]
plot(tmp)
```


partial auto-correlation

```{r}
tmp=pacf(varicelle,type="cor",plot = FALSE)
tmp$acf[1:3,1,1]
plot(tmp)
```

Annual evolution

```{r}

x=rep(0,41)
for (i in 0:40) x[i+1]<-sum(varicelle[(1+12*i):(12*(i+1))])
plot(x,type='l',xaxt='n',xlab='')
axis(1,at = 0:40,labels = 1931:1971)

```

