---
title: "Exercises"
output: html_notebook
---

```{r}
library(forecast)
library(fpp2)
```

```{r}

data = uschange[,"Production"]
autoplot(data)
```

```{r}
head(data)
tail(data)
```

```{r}
Box.test(data)
```



```{r}
ggAcf(data)
```

```{r}
ggPacf(data)
```


```{r}
train = window(x = data,end=c(2015,4))
test = window(x = data,start=c(2016,1))
```

```{r}


```


```{r}
fit1 = Arima(train,order=c(0,0,12))
fit2 = Arima(train,order=c(12,0,0))
```

```{r}
fit1
```

```{r}
fit2
```

```{r}
checkresiduals(fit1)
```

```{r}
checkresiduals(fit2)
```

```{r}
autoplot(forecast(fit1,h=3*4+1),PI=FALSE) +
  autolayer(forecast(fit2,h=3*4+1),PI=FALSE) + 
  coord_cartesian(xlim = c(1970, 2020))
```

************************************************************************************************
EXAMPLE 2:
closing stock prices of GOOG from the NASDAQ exchange, for 1000 consecutive
trading days between 25 February 2013 and 13 February 2017

```{r}
data = goog
autoplot(data)
```

```{r}
Box.test(data)
```

```{r}
ggAcf(data)
```

```{r}
ggPacf(data)
```

```{r}
fit1 = arima(data,order=c(0,1,0))
fit2 = arima(data,order=c(0,2,1))
fit1
fit2

HWd=holt(data,h=5)
HWd[["model"]]
```

```{r}
auto.arima(data)
```


```{r}
checkresiduals(fit1)
```

```{r}
checkresiduals(fit2)
```


```{r}
autoplot(forecast(fit1,h=5),PI=FALSE) +
  autolayer(forecast(fit2,h=5),PI=FALSE) + 
  autolayer(HWd,PI=TRUE) + 
  coord_cartesian(xlim = c(980, 1005))
```

*******************************************************************************************

```{r}
data = goog
autoplot(data)
length(data)
train = window(data,end=995)
test = window(data,start=996)

```

```{r}
train %>% diff(differences=1) %>% ggtsdisplay()
```

SIMPLE EXPONENTIAL SMOOTHING MODEL
```{r}
fit1 = ses(train,h=5)
fit1 %>% residuals() %>% ggtsdisplay()
f1 = forecast(fit1,h=5)
summary(f1)
print("RMSE SES")
RMSE_SES = sqrt(mean((f1$mean-test)^2))
print(RMSE_SES)
```


ARIMA MODEL
```{r}
fit3 = Arima(train,order=c(0,3,3))
fit3 %>% residuals() %>% ggtsdisplay()
f3 = forecast(fit3,h=5)
summary(f3)
print("RMSE ARIMA (0,3,3)")
RMSE_ARIMA = sqrt(mean((f3$mean-test)^2))
print(RMSE_ARIMA)
```

ARIMA MODEL WITH LAMBDA
```{r}
fit4 = Arima(train,order=c(1,3,3),lambda='auto')
fit4 %>% residuals() %>% ggtsdisplay()
f4 = forecast(fit4,h=5)
summary(f4)
print("RMSE ARIMA (0,3,4) BoxCox")
RMSE_ARIMA_L = sqrt(mean((f4$mean-test)^2))
print(RMSE_ARIMA_L)
```

NEURAL NETWORK
```{r}
fit5 = nnetar(train,p=20)
fit5 %>% residuals() %>% ggtsdisplay()
f5 = forecast(fit5,h=5)
summary(f5)
print("RMSE NNET")
RMSE_NNET = sqrt(mean((f5$mean-test)^2))
print(RMSE_NNET)
```

```{r}
autoplot(train) + 
  autolayer(test,series='test') + 
  autolayer(f1,series = "SES",PI=FALSE) + 
  autolayer(f3,series = "ARIMA",PI=FALSE) + 
  autolayer(f4,series="ARIMA BC",PI=FALSE) + 
  autolayer(f5,series="NNET") + 
  coord_cartesian(xlim = c(990,1000),ylim = c(750,850))
```



